spring:
  main:
    web-application-type: servlet
  application:
    name: backend
  profiles:
    active: local
# 로컬에서는 local로 배포시에 prod로 수정

# Swagger 설정 (WebMVC + WebFlux 공존 환경)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  packages-to-scan: com.example.backend
  paths-to-match: /api/**
