spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    # DB 실제 생성후 맞는 유저, 패스워드 입력
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  forward-headers-strategy: framework
ai:
  server:
    url: http://localhost:8888

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region: ap-northeast-2